export const errorTranslations: Readonly<Record<string, string>> = {
  CLIENT_NETWORK_ERROR: '无法连接服务器，请检查网络后手动重试。',
  CLIENT_RESPONSE_INVALID: '服务器响应不符合约定，请稍后重试。',
  HTTP_REQUEST_INVALID: '请求格式不正确，请检查输入。',
  HTTP_NOT_FOUND: '请求的资源不存在。',
  HTTP_METHOD_NOT_ALLOWED: '此操作不受支持。',
  HTTP_INTERNAL_ERROR: '服务器暂时无法完成操作，请稍后重试。',
  AUTHN_CAPTCHA_INVALID: '验证码错误、已过期或已使用，请输入新的验证码。',
  AUTHN_CREDENTIALS_INVALID: '用户名或密码不正确。',
  AUTHN_LOGIN_LOCKED: '登录暂时锁定，请等待倒计时结束后手动重试。',
  AUTHN_REFRESH_TOKEN_INVALID: '会话已失效，请重新登录。',
  AUTHN_TOKEN_INVALID: '会话已失效，请重新登录。',
  AUTHN_HEADER_MISSING: '请先登录。',
  AUTHN_HEADER_INVALID: '认证信息无效，请重新登录。',
  IDENTITY_ACCOUNT_DISABLED: '账号已停用，请联系管理员。',
  IDENTITY_USER_NOT_FOUND: '用户不存在。',
  IDENTITY_PERMISSION_DENIED: '没有权限执行此操作。',
  IDENTITY_VALIDATION_INVALID: '请检查标注的字段。',
  IDENTITY_CONFLICT: '资料与现有记录冲突，请核对后重试。',
  IDENTITY_INTERNAL_ERROR: '用户操作未完成，请稍后重试。',
  IDENTITY_PASSWORD_INVALID: '密码至少 6 位，且包含大写、小写、数字、特殊字符中的至少三类。',
  IDENTITY_PASSWORD_CONFIRMATION_INVALID: '两次输入的密码不一致。',
  IDENTITY_PASSWORD_REUSE: '新密码不能与旧密码相同。',
  IDENTITY_OLD_PASSWORD_INVALID: '原密码不正确。',
  IDENTITY_CURRENT_PASSWORD_INVALID: '当前密码不正确。',
  IDENTITY_ADMIN_EMAIL_NOT_WRITABLE: '邮箱变更须使用个人邮箱验证流程。',
  IDENTITY_EMAIL_VERIFICATION_RATE_LIMITED: '邮箱验证请求过于频繁，请稍后手动重试。',
  IDENTITY_EMAIL_VERIFICATION_DELIVERY_FAILED: '验证邮件暂时无法发送，请稍后重试。',
  IDENTITY_EMAIL_VERIFICATION_INVALID: '邮箱验证链接无效或已过期。',
  AUTHZ_NOT_FOUND: '角色或权限不存在。',
  AUTHZ_CONFLICT: '授权资料发生冲突或受到保护，请重新读取并核对后再提交。',
  AUTHZ_VALIDATION_INVALID: '授权设置不符合规则，请检查选择。',
  AUTHZ_INVALID_USER: '目标用户不允许执行此操作。',
  AUTHZ_PERMISSION_CODE_NOT_FOUND: '所需权限码不存在。',
  AUTHZ_INTERNAL_ERROR: '授权操作未完成，请稍后重试。',
  API_META_NOT_FOUND: '接口配置不存在。',
  API_META_CONFLICT: '接口配置存在冲突。',
  API_META_VALIDATION_INVALID: '接口配置不符合规则。',
  API_META_INTERNAL_ERROR: '权限检查暂时不可用，请稍后重试。',
  API_META_PERMISSION_NOT_CONFIGURED: '此接口尚未配置访问权限。',
  API_META_DISABLED: '此接口已停用。',
  API_META_PERMISSION_MISSING: '此接口缺少权限配置。',
  API_META_PERMISSION_DENIED: '没有访问此功能的权限。',
  NAV_NOT_FOUND: '菜单不存在。', NAV_CONFLICT: '菜单配置存在冲突。',
  NAV_VALIDATION_INVALID: '菜单配置不符合规则。', NAV_INTERNAL_ERROR: '菜单操作未完成，请稍后重试。',
  ORG_NOT_FOUND: '组织不存在。', ORG_CONFLICT: '组织归属发生冲突，请重新读取并核对后再提交。',
  ORG_VALIDATION_INVALID: '组织设置不符合规则，请检查范围与层级。', ORG_INTERNAL_ERROR: '组织操作未完成，请稍后重试。',
  REQUEST_INVALID: '请求格式不正确。', AVATAR_FIELD_NOT_WRITABLE: '头像须通过专用头像入口修改。',
  UPLOAD_BODY_INVALID: '上传格式不正确。', UPLOAD_BODY_TOO_LARGE: '上传内容超过大小限制。',
  UPLOAD_FILE_MISSING: '请选择上传文件。', UPLOAD_MULTIPLE_FILES: '一次只能上传一个文件。',
  FILE_TOO_LARGE: '文件超过大小限制。', FILE_EMPTY: '文件为空。', FILE_TYPE_NOT_ALLOWED: '不支持此文件类型。',
  FILE_TYPE_MISMATCH: '文件类型与内容不一致。', FILE_ENCODING_INVALID: '文件编码不正确。', FILE_CONTENT_INVALID: '文件内容不正确。',
  IMAGE_DIMENSION_LIMIT: '图片尺寸超过限制。', IMAGE_DECODE_INVALID: '图片无法读取。',
  STORAGE_OBJECT_NOT_FOUND: '文件不存在。', STORAGE_UNAVAILABLE: '文件存储暂时不可用。',
  PERSISTENCE_FAILED: '文件保存失败。', INTERNAL_ERROR: '文件操作未完成，请稍后重试。',
};

// Unknown public codes retain only the contract's safe, plain English fallback.
export function safeFallback(value: unknown): string {
  return typeof value === 'string' && value.length > 0 && value.length <= 240 && /^[\x20-\x7e]+$/.test(value)
    ? value : 'Request failed. Please try again.';
}
export function localizedError(code: string, fallback: string): string {
  return errorTranslations[code] ?? safeFallback(fallback);
}
