import * as React from 'react';
import * as Primitive from '@radix-ui/react-dropdown-menu';
import { Check, ChevronRight, Circle } from 'lucide-react';
import { cn } from '@/lib/utils';
export const DropdownMenu = Primitive.Root;
export const DropdownMenuTrigger = Primitive.Trigger;
export const DropdownMenuGroup = Primitive.Group;
export const DropdownMenuPortal = Primitive.Portal;
export const DropdownMenuSub = Primitive.Sub;
export const DropdownMenuRadioGroup = Primitive.RadioGroup;
export const DropdownMenuContent = React.forwardRef<React.ElementRef<typeof Primitive.Content>, React.ComponentPropsWithoutRef<typeof Primitive.Content>>(({ className, sideOffset = 6, collisionPadding = 12, ...props }, ref) => <Primitive.Portal><Primitive.Content ref={ref} className={cn('ui-dropdown-content', className)} sideOffset={sideOffset} collisionPadding={collisionPadding} {...props} /></Primitive.Portal>);
export const DropdownMenuItem = React.forwardRef<React.ElementRef<typeof Primitive.Item>, React.ComponentPropsWithoutRef<typeof Primitive.Item> & { inset?: boolean }>(({ className, inset, ...props }, ref) => <Primitive.Item ref={ref} className={cn('ui-dropdown-item', inset && 'ui-dropdown-inset', className)} {...props} />);
export const DropdownMenuLabel = React.forwardRef<React.ElementRef<typeof Primitive.Label>, React.ComponentPropsWithoutRef<typeof Primitive.Label> & { inset?: boolean }>(({ className, inset, ...props }, ref) => <Primitive.Label ref={ref} className={cn('ui-dropdown-label', inset && 'ui-dropdown-inset', className)} {...props} />);
export const DropdownMenuSeparator = React.forwardRef<React.ElementRef<typeof Primitive.Separator>, React.ComponentPropsWithoutRef<typeof Primitive.Separator>>(({ className, ...props }, ref) => <Primitive.Separator ref={ref} className={cn('ui-dropdown-separator', className)} {...props} />);
export const DropdownMenuCheckboxItem = React.forwardRef<React.ElementRef<typeof Primitive.CheckboxItem>, React.ComponentPropsWithoutRef<typeof Primitive.CheckboxItem>>(({ className, children, checked, ...props }, ref) => <Primitive.CheckboxItem ref={ref} checked={checked} className={cn('ui-dropdown-item ui-dropdown-inset', className)} {...props}><span className="ui-dropdown-indicator"><Primitive.ItemIndicator><Check size={15} /></Primitive.ItemIndicator></span>{children}</Primitive.CheckboxItem>);
export const DropdownMenuRadioItem = React.forwardRef<React.ElementRef<typeof Primitive.RadioItem>, React.ComponentPropsWithoutRef<typeof Primitive.RadioItem>>(({ className, children, ...props }, ref) => <Primitive.RadioItem ref={ref} className={cn('ui-dropdown-item ui-dropdown-inset', className)} {...props}><span className="ui-dropdown-indicator"><Primitive.ItemIndicator><Circle size={10} fill="currentColor" /></Primitive.ItemIndicator></span>{children}</Primitive.RadioItem>);
export const DropdownMenuSubTrigger = React.forwardRef<React.ElementRef<typeof Primitive.SubTrigger>, React.ComponentPropsWithoutRef<typeof Primitive.SubTrigger> & { inset?: boolean }>(({ className, inset, children, ...props }, ref) => <Primitive.SubTrigger ref={ref} className={cn('ui-dropdown-item', inset && 'ui-dropdown-inset', className)} {...props}>{children}<ChevronRight size={16} className="ml-auto" /></Primitive.SubTrigger>);
export const DropdownMenuSubContent = React.forwardRef<React.ElementRef<typeof Primitive.SubContent>, React.ComponentPropsWithoutRef<typeof Primitive.SubContent>>(({ className, ...props }, ref) => <Primitive.SubContent ref={ref} className={cn('ui-dropdown-content', className)} {...props} />);
export const DropdownMenuShortcut = ({ className, ...props }: React.HTMLAttributes<HTMLSpanElement>) => <span className={cn('ml-auto text-xs', className)} {...props} />;
DropdownMenuContent.displayName = 'DropdownMenuContent'; DropdownMenuItem.displayName = 'DropdownMenuItem';
